### ISSUE TITLE
Crop rectangle does not fit within image data.

### ISSUE THREAD

**Issue by super-hu** [TonnyL/Espresso#16]
7.0分屏下，二维码扫描 崩溃
```
java.lang.IllegalArgumentException: Crop rectangle does not fit within image data.
                                                                                 at com.google.zxing.PlanarYUVLuminanceSource.<init>(PlanarYUVLuminanceSource.java:50)
                                                                                 at io.github.marktony.espresso.zxing.decode.DecodeHandler.buildLuminanceSource(DecodeHandler.java:154)
                                                                                 at io.github.marktony.espresso.zxing.decode.DecodeHandler.decode(DecodeHandler.java:95)
                                                                                 at io.github.marktony.espresso.zxing.decode.DecodeHandler.handleMessage(DecodeHandler.java:58)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                 at android.os.Looper.loop(Looper.java:164)
                                                                                 at io.github.marktony.espresso.zxing.decode.DecodeThread.run(DecodeThread.java:98)
```

**Comment by TonnyL** [comment]
Hi, @hcadoid ,

可以参考这个:  https://github.com/journeyapps/zxing-android-embedded/issues/63
